name: github_watcher
description: A simple Flutter Android app to watch recent commits from GitHub repositories.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^17.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
